[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"

remappings = [
    "@uniswap/v4-core/src/=lib/v4-core/src/",
    "@uniswap/v4-core/=lib/v4-core/src/",
    "v4-core/src/=lib/v4-core/src/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@fhenixprotocol/cofhe-contracts/=lib/cofhe-contracts/contracts/",
    "cofhe-contracts/=lib/cofhe-contracts/contracts/"
]
